"""The picker's logic, in node, against a REAL preview and the REAL part library.

The payloads are generated by the actual pipeline and interpolated into the script,
so a field renamed on the wire fails here rather than emptying the picker in a
browser nobody is watching — the pattern `test_part_drawer_module.py` established.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from fenceai.catalog.demo import demo_catalog
from fenceai.fencemodel.demo import demo_models
from fenceai.fencemodel.preview import PreviewRequest, preview_panel
from fenceai.parts.demo import demo_parts
from fenceai.parts.model import PartLibrary

STATIC = Path(__file__).resolve().parents[2] / "src" / "fenceai" / "web" / "static"

SCRIPT = """
import { eligibilitySource, partsByType, specChips, partSummary }
  from "./js/panel-model.js";

const parts = %(parts)s;
const preview = %(preview)s;
const out = {};

out.sources = {
  part: eligibilitySource({ part_id: "rail-38", eligibility: { members: [] } }),
  members: eligibilitySource({ part_id: "",
    eligibility: { members: [{ sku: "RAIL-3000" }] } }),
  predicate: eligibilitySource({ part_id: "",
    eligibility: { members: [], predicate: { op: "cmp" } } }),
  nothing: eligibilitySource({ part_id: "", eligibility: { members: [] } }),
  partWins: eligibilitySource({ part_id: "rail-38",
    eligibility: { members: [], predicate: { op: "cmp" } } }),
  missingReq: eligibilitySource(null),
};

const grouped = partsByType(parts);
out.groups = grouped.map((g) => [g.type, g.parts.map((p) => p.id)]);

out.chips = specChips(parts.find((p) => p.id === "rail-38-vinyl"))
  .map((c) => c.text);
out.chipsOfSkuPart = specChips(parts.find((p) => p.id === "rail-rail-3000"))
  .map((c) => c.text);
out.chipsOfNothing = specChips(null);

const summary = partSummary(
  { part_id: "rail-rail-3000", eligibility: { members: [] } },
  { parts, preview, slotKey: "rail" });
out.summary = { source: summary.source, id: summary.part?.id,
                candidates: summary.candidates, chosen: summary.chosen,
                missing: summary.missing };

out.unknownPart = partSummary(
  { part_id: "no-such-part", eligibility: { members: [] } },
  { parts, preview, slotKey: "rail" }).missing;

console.log(JSON.stringify(out));
"""


@pytest.mark.skipif(not shutil.which("node"), reason="node not available")
def test_the_picker_reads_the_real_library_and_the_real_preview(tmp_path):
    library = PartLibrary(parts=demo_parts())
    # `part_library=`, not `parts=` — preview_panel already has a local `parts`
    # (the priced rows it returns) and says so in its own signature comment
    preview = preview_panel(
        demo_models()["M-SLAT"], PreviewRequest(height_mm=1800, width_mm=2400),
        demo_catalog(), part_library=library)
    payload = SCRIPT % {
        "parts": json.dumps([p.model_dump() for p in library.parts]),
        "preview": preview.model_dump_json(),
    }
    script = STATIC / "_picker_test.mjs"
    script.write_text(payload)
    try:
        proc = subprocess.run(["node", str(script)], capture_output=True,
                              text=True, cwd=STATIC, timeout=60)
    finally:
        script.unlink()
    assert proc.returncode == 0, proc.stderr
    out = json.loads(proc.stdout)

    # the four shapes, and the one that must win
    assert out["sources"] == {
        "part": "part", "members": "authored_members",
        "predicate": "authored_predicate", "nothing": "unspecified",
        "partWins": "part", "missingReq": "unspecified",
    }

    # grouped by type, both levels sorted, so the picker never reshuffles
    types = [g[0] for g in out["groups"]]
    assert types == sorted(types)
    for _type, ids in out["groups"]:
        assert ids == sorted(ids)
    assert "rail" in types

    # a spec-authored part shows what it requires; a sku-list part says so plainly
    assert any("38" in c for c in out["chips"])
    assert any("vinyl" in c.lower() for c in out["chips"])
    assert out["chipsOfSkuPart"]      # not empty — an sku list is still a fact
    assert out["chipsOfNothing"] == []

    # the summary joins the slot, the library and the preview
    assert out["summary"]["source"] == "part"
    assert out["summary"]["id"] == "rail-rail-3000"
    assert out["summary"]["candidates"] >= 1
    assert out["summary"]["chosen"]
    assert out["summary"]["missing"] is False

    # a part_id the library does not have is REPORTED, never rendered as empty
    assert out["unknownPart"] is True
