"""The material & inventory drawer's join (static/js/part-drawer.js).

Three documents meet on one SKU here — the resolved panel's eligibility, the
catalog, and the project's inventory — and each of the three joins has a way of
being wrong that looks perfectly fine on screen:

  * offering the CATALOG instead of the slot's own eligibility. A gate kit in the
    screw slot's dropdown is refused by the API only after the click, and the
    person has already decided by then;
  * adding remnants to whole units. "3 in stock" where the stock is three 300 mm
    offcuts promises a post that does not exist;
  * showing a rate-priced product's per-metre figure in a column of per-unit
    prices, so a 6 m bar looks cheaper than a 3 m one.

The preview is generated by the REAL pipeline (`preview_panel`) and interpolated
into the script, so a field renamed on the wire fails here rather than emptying
the drawer in a browser nobody is watching.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

from fenceai.catalog.demo import demo_catalog
from fenceai.catalog.model import purchase_price_cents
from fenceai.fencemodel.demo import demo_models
from fenceai.fencemodel.preview import PreviewRequest, preview_panel
from tests.fencemodel.test_preview import two_candidate_model
from fenceai.fulfillment.fulfill import Inventory, InventoryItem

STATIC = Path(__file__).resolve().parents[2] / "src" / "fenceai" / "web" / "static"

SCRIPT = """
import { readFileSync } from "node:fs";
globalThis.localStorage = {
  s: {}, getItem: (k) => globalThis.localStorage.s[k] ?? null,
  setItem: (k, v) => { globalThis.localStorage.s[k] = String(v); },
};
globalThis.document = { getElementById: () => null, querySelectorAll: () => [],
                        documentElement: {} };
globalThis.fetch = async (url) => ({
  ok: true, json: async () => JSON.parse(readFileSync(url, "utf8")),
});

import { initI18n, setLocale } from "./js/i18n.js";
import { drawerHtml, partOptions, stockBySku, swatch } from "./js/part-drawer.js";

await initI18n();
await setLocale("en");

const preview = %(preview)s;
const products = %(products)s;
const inventory = %(inventory)s;
// a slot with a REAL alternative. Every built-in slot names exactly one eligible
// product, so an option table built from one of those is a table of one row —
// and the pick button, the delta column and the chosen/offer fork are then all
// asserted as 0 == 0.
const twoWay = %(two_way)s;
const pinned = %(pinned)s;

const out = {};
const slat = partOptions(preview, "slat", { products, inventory });
out.slat = {
  role: slat.role, qty: slat.qty, length: slat.length_mm,
  options: slat.options.map((o) => ({
    sku: o.sku, chosen: o.chosen, material: o.material, finish: o.finish,
    colour: o.colour, price: o.price_cents, delta: o.delta_cents,
    bought_as: o.bought_as, on_hand: o.on_hand, remnants: o.remnants,
  })),
};
out.rail_options = partOptions(preview, "rail", { products, inventory })
  .options.map((o) => o.sku);
out.missing_slot = partOptions(preview, "no-such-slot", { products, inventory });

// stock: units and remnants are different things and are never summed
out.stock = [...stockBySku(inventory).entries()]
  .map(([sku, row]) => [sku, row.units, row.remnants.map((r) => r.length_mm),
                        row.remnants.map((r) => r.id)]);
out.stock_of_nothing = [...stockBySku(null).entries()].length;

// a colour only paints if it is a plain hex triple
out.swatches = ["#a16207", "#A16207", "red", "#a16207;background:url(x)",
                "#abc", "", null, 42].map(swatch);

// the rendered drawer: every product named, the chosen one marked, and a button
// per alternative — plus no unescaped angle bracket from any server string
const html = drawerHtml(slat, { locale: "en" });
out.html = {
  has_each_sku: slat.options.every((o) => html.includes(o.sku)),
  buttons: (html.match(/data-pick-sku="/g) || []).length,
  chosen_tags: (html.match(/tag active/g) || []).length,
  swatch_styles: (html.match(/background:#[0-9a-fA-F]{6}/g) || []).length,
  says_stock_scope: html.includes("no warehouse scope"),
  raw_script: html.includes("<script"),
};

// the alternatives, which are the drawer's reason to exist
const rail = partOptions(twoWay, "rail", { products, inventory });
out.two_way = {
  skus: rail.options.map((o) => o.sku),
  chosen: rail.options.filter((o) => o.chosen).map((o) => o.sku),
  deltas: rail.options.map((o) => o.delta_cents),
  prices: rail.options.map((o) => o.price_cents),
};
const twoWayHtml = drawerHtml(rail, { locale: "en" });
out.two_way_html = {
  buttons: (twoWayHtml.match(/data-pick-sku="/g) || []).length,
  offers_the_other: twoWayHtml.includes('data-pick-sku="SLAT-100"'),
  shows_delta: twoWayHtml.includes("+₪36.00"),
  chosen_tags: (twoWayHtml.match(/tag active/g) || []).length,
};
// once a product is PINNED its own eligibility is that product alone — correct
// for pricing, useless as a list. The table is built from the unpinned baseline.
const pinnedRail = partOptions(pinned, "rail", { products, inventory, catalogue: twoWay });
out.pinned = {
  skus: pinnedRail.options.map((o) => o.sku),
  chosen: pinnedRail.options.filter((o) => o.chosen).map((o) => o.sku),
  buttons: (drawerHtml(pinnedRail, { locale: "en", pinned: "SLAT-100" })
    .match(/data-pick-sku="/g) || []).length,
};
// and without the baseline it collapses, which is the defect this argument is about
out.pinned_without_catalogue =
  partOptions(pinned, "rail", { products, inventory }).options.map((o) => o.sku);

// the per-unit price comes off the wire, not out of a second rounding here.
// The rate is deliberately one the client's old formula would ALSO have got
// right, so the assertion is about which number is read, not about arithmetic.
const bare = (p) => partOptions(
  { parts: [{ slot_key: "x", role: "rail", qty: 1, sku: "P",
              eligible_skus: ["P"] }] },
  "x", { products: { P: p } }).options[0].price_cents;
out.rate_priced = {
  wire: 1850,
  shown: bare({ sku: "P", price_cents: 0, purchase_price_cents: 1850,
                pricing: { kind: "linear", cents_per_m: 600 },
                consumption: { kind: "divisible_linear",
                               purchase_length_mm: 3000 } }),
  // and the field WINS over anything derivable here: a server that starts
  // charging a minimum must not be silently overruled by the client
  overrides_the_rate: bare({ sku: "P", price_cents: 0, purchase_price_cents: 9900,
                             pricing: { kind: "linear", cents_per_m: 600 },
                             consumption: { kind: "divisible_linear",
                                            purchase_length_mm: 3000 } }),
};
out.legacy_flat = bare({ sku: "P", price_cents: 2500, pricing: { kind: "flat" } });
out.legacy_rate = bare({ sku: "P", price_cents: 0,
                         pricing: { kind: "linear", cents_per_m: 600 },
                         consumption: { kind: "divisible_linear",
                                        purchase_length_mm: 3000 } });

// what is LEFT after this fence: the yard's four bars are not four bars to
// change your mind with if this run has already been allocated three of them
const allocated = [
  { inventory_item_id: "i1", sku: "SLAT-100", qty: 3, length_used_mm: null },
  { inventory_item_id: "i2", sku: "SLAT-100", qty: 0, length_used_mm: 850 },
];
const net = partOptions(preview, "slat", { products, inventory,
                                           allocations: allocated }).options[0];
out.net = {
  on_hand: net.on_hand, committed: net.committed, available: net.available,
  remnants: net.remnants, committed_remnants: net.committed_remnants,
};
out.net_html = drawerHtml(
  partOptions(preview, "slat", { products, inventory, allocations: allocated }),
  { locale: "en" });
// over-allocation floors at zero rather than going negative
out.over = partOptions(preview, "slat", { products, inventory, allocations: [
  { inventory_item_id: "i1", sku: "SLAT-100", qty: 99, length_used_mm: null },
] }).options[0].available;
// and with no allocations at all, available is simply what is on hand
out.no_allocations = partOptions(preview, "slat", { products, inventory })
  .options[0];

// a hostile catalog: the name is server text and must not become markup
const hostile = JSON.parse(JSON.stringify(products));
const anySku = slat.options[0].sku;
hostile[anySku].name = "<img src=x onerror=alert(1)>";
hostile[anySku].name_i18n = {};
hostile[anySku].attrs = { ...hostile[anySku].attrs, colour: "#fff;background:url(x)" };
const hostileHtml = drawerHtml(
  partOptions(preview, "slat", { products: hostile, inventory }), { locale: "en" });
out.hostile = {
  escaped: hostileHtml.includes("&lt;img") && !hostileHtml.includes("<img"),
  no_bad_swatch: !hostileHtml.includes("url(x)"),
};

console.log(JSON.stringify(out));
"""


@pytest.fixture(scope="module")
def drawer():
    node = shutil.which("node")
    if not node:
        pytest.skip("node not available")
    catalog = demo_catalog()
    model = demo_models()["M-SLAT"]
    preview = preview_panel(model, PreviewRequest(height_mm=1800, width_mm=2500), catalog)
    inventory = Inventory(items=[
        InventoryItem(id="i1", sku="SLAT-100", kind="full_stock", qty=4),
        InventoryItem(id="i2", sku="SLAT-100", kind="remnant", length_mm=900),
        InventoryItem(id="i3", sku="SLAT-100", kind="remnant", length_mm=450),
        InventoryItem(id="i4", sku="RAIL-3000", kind="opened_package", qty=2),
    ])
    two_way_model = two_candidate_model()
    request = PreviewRequest(height_mm=1800, width_mm=2500)
    script = SCRIPT % {
        "preview": preview.model_dump_json(),
        # exactly what `/api/catalog` serves, folded the way `loadCatalogProducts`
        # folds it: the derived per-unit price rides along, because the client no
        # longer works it out
        "products": json.dumps({
            s: {**p.model_dump(), "purchase_price_cents": purchase_price_cents(p)}
            for s, p in catalog.products.items()}),
        "inventory": inventory.model_dump_json(),
        "two_way": preview_panel(two_way_model, request, catalog).model_dump_json(),
        "pinned": preview_panel(
            two_way_model,
            request.model_copy(update={"slot_skus": {"rail": "SLAT-100"}}),
            catalog).model_dump_json(),
    }
    proc = subprocess.run(
        [node, "--input-type=module", "-e", script],
        cwd=STATIC, capture_output=True, text=True, check=False,
    )
    assert proc.returncode == 0, proc.stderr
    return json.loads(proc.stdout)


def test_only_the_slots_own_eligible_products_are_offered(drawer):
    """The whole catalog is 12 products. A drawer that offered them would let
    someone pick a gate kit for a slat, and the API refuses that only after the
    click has already made the decision feel made."""
    skus = [o["sku"] for o in drawer["slat"]["options"]]
    assert skus == ["SLAT-100"], skus
    assert drawer["rail_options"] == ["RAIL-3000"]
    assert "GATE-KIT-1000" not in skus


def test_a_slot_this_bay_does_not_have_opens_no_drawer(drawer):
    """Legitimate, not an error: a fitted pattern can place none of a member."""
    assert drawer["missing_slot"] is None


def test_the_chosen_product_is_marked_and_priced_at_zero_delta(drawer):
    chosen = [o for o in drawer["slat"]["options"] if o["chosen"]]
    assert len(chosen) == 1
    assert chosen[0]["delta"] == 0
    assert chosen[0]["price"] == 5400        # SLAT-100, one 6000 mm bar


def test_material_and_finish_come_from_the_catalog_not_from_the_sku(drawer):
    """Read off `attrs`. Parsing "SLAT-100" for a material is the mistake the
    gate-kit width already taught this codebase not to repeat."""
    option = drawer["slat"]["options"][0]
    assert option["material"] and option["finish"]
    assert option["bought_as"] == "divisible_linear"


def test_whole_units_and_offcuts_are_counted_separately(drawer):
    """Four bars and two offcuts is not "six in stock": the cut planner keeps
    them in different bins, and so must the column that reports them."""
    option = drawer["slat"]["options"][0]
    assert option["on_hand"] == 4
    assert option["remnants"] == [450, 900]   # sorted, longest last
    stock = dict((sku, (units, rem, ids)) for sku, units, rem, ids in drawer["stock"])
    assert stock["SLAT-100"] == (4, [450, 900], ["i3", "i2"])
    assert stock["RAIL-3000"] == (2, [], [])  # an opened package is still units
    assert drawer["stock_of_nothing"] == 0


def test_only_a_plain_hex_triple_is_allowed_to_paint(drawer):
    """The second gate on a value that reaches a CSS `background`. The catalog
    validates it at load; this is the client refusing to trust that alone,
    because esc() guarantees nothing in a style context."""
    assert drawer["swatches"] == [
        "#a16207", "#A16207", None, None, None, None, None, None,
    ]


def test_the_rendered_drawer_names_every_option_and_offers_the_others(drawer):
    html = drawer["html"]
    assert html["has_each_sku"]
    assert html["chosen_tags"] == 1
    assert html["buttons"] == len(drawer["slat"]["options"]) - 1
    assert html["swatch_styles"] >= 1
    assert html["says_stock_scope"], "the no-warehouse-scope caveat is not optional"
    assert not html["raw_script"]


def test_a_hostile_product_name_and_colour_cannot_escape(drawer):
    """Product names and attrs are server text, and a catalog is editable through
    the API. Both go somewhere dangerous — one into innerHTML, one into paint."""
    assert drawer["hostile"]["escaped"]
    assert drawer["hostile"]["no_bad_swatch"]


# --- the alternatives, which are the drawer's reason to exist ---------------

def test_a_slot_with_a_real_alternative_offers_it(drawer):
    """Every built-in slot names exactly one eligible product, so a drawer tested
    only against those asserts "0 alternatives were offered" and passes with the
    offer branch deleted. This slot has two that genuinely cost different
    amounts: RAIL-3000 (a 3000 mm bar at 1800c) and SLAT-100 (6000 mm at 5400c),
    both able to supply a 2500 mm rail."""
    assert drawer["two_way"]["skus"] == ["RAIL-3000", "SLAT-100"]
    assert drawer["two_way"]["chosen"] == ["RAIL-3000"], "least cost wins by default"
    assert drawer["two_way"]["prices"] == [1800, 5400]
    # the delta is per PURCHASE UNIT, the only honest comparison before cutting
    assert drawer["two_way"]["deltas"] == [0, 3600]


def test_the_rendered_drawer_offers_the_alternative_and_prices_the_difference(drawer):
    html = drawer["two_way_html"]
    assert html["buttons"] == 1, "one button per product that is not the chosen one"
    assert html["offers_the_other"]
    assert html["shows_delta"], "a signed difference is what the column is for"
    assert html["chosen_tags"] == 1


def test_pinning_a_product_does_not_destroy_the_list_it_was_picked_from(drawer):
    """A pin narrows that slot's eligibility — correct, and what makes the price
    honest — so the pinned preview's `eligible_skus` is the pinned product alone.
    Building the table from it collapsed the comparison to one row on the first
    click, with no way to try a third product or go back. The list is a property
    of the SLOT; only the price and the marker come from the choice."""
    assert drawer["pinned"]["skus"] == ["RAIL-3000", "SLAT-100"]
    assert drawer["pinned"]["chosen"] == ["SLAT-100"], "the pin is what was priced"
    assert drawer["pinned"]["buttons"] == 1, "the other product is still offered"
    # the defect, pinned as its own fact so the fix cannot be quietly undone
    assert drawer["pinned_without_catalogue"] == ["SLAT-100"]


def test_the_per_unit_price_is_the_servers_and_not_a_second_rounding(drawer):
    """`purchase_price_cents` is what the catalog module's own docstring calls
    THE rounding point for rate pricing — "nothing upstream rounds and nothing
    downstream re-rounds, or two call sites differ by a cent and the same BOM
    totals two ways". The drawer had been the downstream that re-rounded."""
    # 600 c/m over a 3000 mm bar: one purchase unit, rounded once, by the server
    assert drawer["rate_priced"]["shown"] == drawer["rate_priced"]["wire"] == 1850
    # and the server's figure wins over anything the client could derive — which
    # is the whole point the first time a minimum charge or waste factor lands
    assert drawer["rate_priced"]["overrides_the_rate"] == 9900
    # and a product fetched from a catalog that does not carry the field yet
    assert drawer["legacy_flat"] == 2500      # a flat price needs no derivation
    assert drawer["legacy_rate"] is None      # a rate without it is not a price


# --- what is left after this run ------------------------------------------

def test_availability_is_the_shelf_less_what_this_fence_already_takes(drawer):
    """The yard's four bars are not four bars available to a change of mind if
    the fence being priced has already been allocated three of them. The first
    version of this column read the inventory alone and said "4" about a product
    with one to spare."""
    net = drawer["net"]
    assert net["on_hand"] == 4
    assert net["committed"] == 3
    assert net["available"] == 1


def test_an_offcut_this_run_is_cutting_from_is_not_offered_twice(drawer):
    """The planner takes a remnant as a whole BIN, so half of one is not left
    over: whatever survives comes back as a PROJECTED remnant, which is a
    different item and not stock on hand."""
    net = drawer["net"]
    assert net["remnants"] == [450], "the 900 mm offcut is being cut from"
    assert net["committed_remnants"] == 1


def test_the_three_stock_facts_are_all_said_never_collapsed(drawer):
    """A single netted figure answers "can I use this" and hides why it is lower
    than the shelf — which is the question a reader asks next."""
    html = drawer["net_html"]
    assert "of 4 on hand, 3 already on this fence" in html
    assert "already being cut from" in html


def test_over_allocation_floors_at_none_rather_than_going_negative(drawer):
    assert drawer["over"] == 0


def test_with_nothing_allocated_availability_is_simply_the_shelf(drawer):
    row = drawer["no_allocations"]
    assert (row["on_hand"], row["committed"], row["available"]) == (4, 0, 4)
    assert row["remnants"] == [450, 900]
